Armour = java.import('code.Armour')
Character = java.import('code.Character')
Creator = java.import('code.Creator')
Item = java.import('code.Item')
Shield = java.import('code.Shield')
Support = java.import('code.Support')
UI = java.import('code.UI')
Util = java.import('code.Util')
Weapon = java.import('code.Weapon')
System = java.import('java.lang.System')
UI:message('Initialized!')