Character = java.import('code.Character')
Creator = java.import('code.Creator')
Item = java.import('code.Item')
UI = java.import('code.UI')
Util = java.import('code.Util')
System = java.import('java.lang.System')
UI:message('Initialized!')